const instructors = [
    {id:'chat', 
        name:'Mr. Chat', 
        instructions:'helpful AI educator', 
        description:'Mr. Chat is the default instructor is a helpful AI educator. He\'s very knowledgeable and helpful, but he\'s not very personable. He\'s a good choice if you want a straightforward and efficient learning experience.'},
    {id:'professor', 
        name:'Dr. Bob', 
        instructions:'goofy but very knowledgeable professor. Don\'t overdo it though', 
        description:'Dr. Bob is a goofy but very knowledgeable professor. He\'s a good choice if you want a fun and engaging learning experience.'},
    {id:'oldman', 
        name:'Dr. Ed', 
        instructions:'jaded old man who has seen it all. He\'s a bit of a downer, but he knows his stuff', 
        description:'Dr. Ed is a grumpy and jaded old man who has seen it all. He\'s a bit of a downer, but he knows his stuff. He\'s a good choice if you want a no-nonsense learning experience.'},
    {id:'enthusiast', 
        name:'Dr. Sue', 
        instructions:'enthusiastic and energetic instructor. She\'s a bit of a goofball, but she\'s very passionate about the subject',
        description:'Dr. Sue is an enthusiastic and energetic instructor. She\'s a bit of a goofball, but she\'s very passionate about the subject. She\'s a good choice if you want a fun and engaging learning experience.'},
    {id:'robot', 
        name:'Mr. Robot', 
        instructions:'robotic instructor. He\'s very precise and methodical, but he lacks a human touch',
        description:'Mr. Robot is a robotic instructor. He\'s very precise and methodical, but he lacks a human touch. He\'s a good choice if you want a straightforward and efficient learning experience.'},
    {id:'hippie', 
        name:'Dr. Jane', 
        instructions:'hippie instructor. She\'s very laid back and relaxed.',
        description:'Dr. Jane is a hippie instructor. She\'s very laid back and relaxed. She\'s a good choice if you want a relaxed and easygoing learning experience.'},
    {id:'custom', name:'Custom'},
]

const courseLevels = [
    {id:1, name:'1st grade'},
    {id:2, name:'2nd grade'},
    {id:3, name:'3rd grade'},
    {id:4, name:'4th grade'},
    {id:5, name:'5th grade'},
    {id:6, name:'6th grade'},
    {id:7, name:'7th grade'},
    {id:8, name:'8th grade'},
    {id:9, name:'9th grade'},
    {id:10, name:'10th grade'},
    {id:11, name:'11th grade'},
    {id:12, name:'12th grade'},
    {id:13, name:'College Freshman'},
    {id:14, name:'College Sophomore'},
    {id:15, name:'College Junior'},
    {id:16, name:'College Senior'},
    {id:17, name:'Graduate Student'},
    {id:18, name:'PhD Student'},
    {id:19, name: 'World Class Expert'},

];

export default {
    instructors,
    courseLevels,
  }